### ISSUE TITLE
Possible redundant line of code?

### ISSUE THREAD

**Issue by Rodrun** [TeamLe-Shop/das-forum#1]
In server.h, there is 

```
struct Server { 
...
}
```

[view](http://j.mp/lineno10)
and `typedef struct Server Server;` [view](http://j.mp/lineno15)

Could line 15 be redundant? You could easily do:

```
typdef struct Server { 
...
} Server;
```

and remove line 15.

**Comment by crumblingstatue** [comment]
CHA-LA
HEAD CHA-LA

**Comment by crumblingstatue** [comment]
![](http://i.imgur.com/Xln2yva.png)

**Comment by pastagatsan** [comment]
I honestly just prefer doing it that way. I am completely aware of that method.
However, dasforum should be readable and have little redundancy, so I will consider changing those struct definitions.

Thanks!

**Comment by Rodrun** [comment]
No problem, just exercising my source code reading skills.
I'm not so good at it.
