### ISSUE TITLE
Pragma once instead?

### ISSUE THREAD

**Issue by Rodrun** [TeamLe-Shop/das-forum#2]
Just ANOTHER possible issue. 

I noticed gatsan using the ifndef guard stuff

```
#ifndef ...
#define ...
#endif
```

Could you replace that with `#pragma once`? Or is that only a C++ thing?

I read earlier that it's _faster_ than the guards. If I'm wrong, please explain.

**EDIT:** 
Yes, I do understand it only affects compile time!

Thanks.

**Comment by pastagatsan** [comment]
Probably a compiler specific thing. To my understanding, this is only in C++.

**Comment by Rodrun** [comment]
I read that it works on multiple compilers, GCC for example. I assume you are using one of ![these compilers](http://en.wikipedia.org/wiki/Pragma_once#Portability).

**Comment by crumblingstatue** [comment]
It's not C++-only, it works with C too, but it's a non-standard extension.
It is, however, supported for all compilers I care about.

**Comment by pastagatsan** [comment]
I probably wont be using non-standard extensions. I assume both Clang and GCC support `#pragma once`, anyways?

**Comment by pastagatsan** [comment]
Also, regarding speed of guards and `#pragma once`... it's a preprocessor thing, done at compile time.

**Comment by Rodrun** [comment]
@crumblingstatue Same here
@JavaCakess I know, I was just suggesting you do that, maybe just have like a 1ms copmile time decrease. Just trying to make files a little smaller, by a few bytes, lidl
